# Generated by Django 3.1.1 on 2023-01-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EMP_ID', models.CharField(help_text='reference number', max_length=20, primary_key=True, serialize=False)),
                ('ENAME', models.CharField(max_length=100)),
                ('POST', models.CharField(max_length=100)),
                ('SALARY', models.IntegerField()),
                ('AGE', models.IntegerField(null=32)),
            ],
        ),
    ]
